[meta]
title = "Node Text Intelligence Starter"
description = "Get started using Deepgram's Text Intelligence with this Node demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "TextIntel"
language = "JavaScript"
framework = "Node"
sdk = "4.11.2"

[pre-build]
command = "pnpm install"
message = "Dependencies installed"

[build]
command = "pnpm build"
message = "Build completed"

[config]
sample = "sample.env"
output = ".env"

[post-build]
message = "Run `pnpm start` to get up and running."
