[meta]
title = "Node Text Intelligence Starter"
description = "Get started using Deepgram's Text Intelligence with this Node demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "TextIntel"
language = "JavaScript"
framework = "Node"
sdk = "4.11.2"

[build]
command = "npm install"

[config]
sample = "sample.env"
output = ".env"

[post-build]
message = "Run `npm start` to start the server."
